### ISSUE TITLE
report_output:error: gen_report input variables less than 6

### ISSUE THREAD

**Issue by osmboy** [ecurtin/spark-bench#65]
when i execute the following command:

```
<SPARK_BENCH_HOME>/<Workload>/bin/gen_data.sh
<SPARK_BENCH_HOME>/<Workload>/bin/run.sh
```
i got error from `num/bench-report.dat`

```
##Apptype,start_ts,duration,size,throughput,resStatus,AppType,nExe,driverMem,exeMem,exeCore,nPar,nIter,memoryFraction,numRecords(size)
error: gen_report input variables less than 6
,Terasort-MLlibConfig,,,,,2,3,,1000
#Apptype,start_ts,duration,size,throughput,resStatus,AppType,nExe,driverMem,exeMem,exeCore,nPar,nIter,memoryFraction,numRecords(size)
error: gen_report input variables less than 6
,Terasort-MLlibConfig,,,,,2,3,,1000

```

**Comment by ecurtin** [comment]
Hi @RayOsLei 
I saw you also opened this issue in SparkTC/spark-bench as https://github.com/SparkTC/spark-bench/issues/48.

ecurtin/spark-bench is basically a rewrite of the entire spark-bench infrastructure. If you're interested, I'd encourage you to peruse the README, check out the examples, and browse the docs. I'm also just about to release a new version on master :)

This fork is **not** feature-complete with old spark-bench _yet_. We've only ported a very select few of the existing benchmark workloads to serve as working examples as we focus on the core architecture. 

I'm going to close this bug here as it relates only to SparkTC/spark-bench, but it will remain open in SparkTC/spark-bench. If you have questions about ecurtin/spark-bench, please don't hesitate to open a new issue and tag it as Question or Feedback.

Thanks!
